# Generated by Django 3.2.5 on 2022-08-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField(unique=True)),
                ('buyer_name', models.CharField(max_length=264)),
                ('buyer_account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(unique=True)),
                ('house_name', models.CharField(max_length=264)),
                ('house_area', models.CharField(max_length=264)),
                ('no_of_bed', models.IntegerField()),
                ('no_of_bath', models.IntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_main_pic', models.ImageField(blank=True, upload_to=None)),
                ('house_detail_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(unique=True)),
                ('owner_name', models.CharField(max_length=264)),
                ('owner_type', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction_end_time', models.TimeField()),
                ('highest_bidder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autionapp.buyer')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autionapp.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autionapp.owner'),
        ),
    ]
