# Generated by Django 3.2.5 on 2022-08-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.CharField(default='a@gmail.com', max_length=264),
        ),
    ]
