# Generated by Django 3.2.5 on 2022-08-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0002_buyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
    ]
