# Generated by Django 3.2.5 on 2022-08-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0004_auto_20220808_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='auction_end_time',
        ),
        migrations.AddField(
            model_name='house',
            name='auction_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
