# Generated by Django 3.2.5 on 2022-08-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0005_auto_20220809_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtrans',
            name='auction_end_time',
        ),
    ]
