# Generated by Django 3.2.5 on 2022-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0007_alter_newtrans_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='max_bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
