# Generated by Django 3.2.5 on 2022-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0008_house_max_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='auction_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='list_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='starting_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_area',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
