# Generated by Django 3.2.5 on 2022-08-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0010_auto_20220810_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='auction_end_time',
        ),
    ]
