# Generated by Django 3.2.5 on 2022-08-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0011_remove_house_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='list_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='max_bid_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='starting_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
