# Generated by Django 3.2.5 on 2022-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0012_auto_20220810_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='max_bid_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
