# Generated by Django 3.2.5 on 2022-09-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0014_alter_house_max_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='max_bid_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
