# Generated by Django 3.2.5 on 2022-09-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0015_alter_house_max_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='max_bidder',
            field=models.CharField(default='None', max_length=264),
        ),
    ]
