# Generated by Django 3.2.5 on 2022-09-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0016_house_max_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtrans',
            name='username',
        ),
        migrations.AddField(
            model_name='newtrans',
            name='Bidder',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
