# Generated by Django 3.2.5 on 2022-09-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autionapp', '0017_auto_20220906_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='list_price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='house',
            name='max_bid_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='house',
            name='starting_price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_area',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='newtrans',
            name='highest_bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
